services:
  - type: web
    name: banco-digital-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: H2_CONSOLE_ENABLED
        value: false
